In [1]:
#loading libaries

!pip install eli5
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold, cross_val_score, StratifiedKFold
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import confusion_matrix, f1_score, precision_recall_curve
from sklearn.metrics import make_scorer, roc_auc_score, auc, precision_score, recall_score, classification_report, roc_curve, accuracy_score, f1_score
from sklearn.linear_model import LogisticRegression
from imblearn.over_sampling import SMOTE
random_state=147
np.random.seed(random_state)
import warnings
warnings.filterwarnings('ignore')

In [2]:
os.chdir('C:/Users/spoorthi/Desktop/project2')
os.getcwd()

'C:\\Users\\spoorthi\\Desktop\\project2'

In [3]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [4]:
train.shape

(200000, 202)

In [5]:
# Using Stratified sampling
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train.drop(['target', 'ID_code'], axis=1), train['target'], test_size=0.3, random_state=147, stratify=train.target)
print('Shape:',X_train.shape, X_test.shape, y_train.shape, y_test.shape)

Shape: (140000, 200) (60000, 200) (140000,) (60000,)


In [6]:
# importing classifiers
from sklearn.tree import DecisionTreeClassifier

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

In [19]:
models = []
models.append(( 'LR' , LogisticRegression(solver='liblinear')))
models.append(( 'CART' ,DecisionTreeClassifier ()))
models.append(( 'NB' , GaussianNB()))
models.append(('RFC', RandomForestClassifier()))

In [9]:
def cv_auc_score(models,scoring, num_folds=3):
    seed = 147 
    results = []
    names = []
    
    print('-> 3-Fold cross-validation ',scoring.__name__,'score for the training data for 4 classifiers.')
    for name, model in models:
        kfold = KFold( n_splits=num_folds, random_state=seed)
        cv_results = cross_val_score(model, X_train, y_train, cv=kfold,verbose=3 ,scoring=make_scorer(scoring))
        results.append(cv_results)
        names.append(name)
        print("Algo: ", name,'::',np.mean(cv_results))

In [10]:
# AUC score
num_folds = 3
scoring=roc_auc_score
print("Scores without StandardScale")
cv_auc_score(models, scoring=scoring, num_folds=num_folds)

Scores without StandardScale
-> 3-Fold cross-validation  roc_auc_score score for the training data for 4 classifiers.
[CV]  ................................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .................................... , score=0.624, total= 1.8min
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.8min remaining:    0.0s


[CV] .................................... , score=0.628, total= 1.7min
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  3.5min remaining:    0.0s


[CV] .................................... , score=0.628, total= 1.9min
Algo:  LR :: 0.6264835546403751
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:  5.4min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .................................... , score=0.559, total= 2.1min
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  2.1min remaining:    0.0s


[CV] .................................... , score=0.562, total= 2.0min
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  4.1min remaining:    0.0s


[CV] .................................... , score=0.561, total=10.0min
Algo:  CART :: 0.5605205214209749
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed: 14.1min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .................................... , score=0.668, total=   1.1s
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.0s remaining:    0.0s


[CV] .................................... , score=0.675, total=   0.9s
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    1.9s remaining:    0.0s


[CV] .................................... , score=0.679, total=   1.0s
Algo:  NB :: 0.6741809150880748
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    2.9s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .................................... , score=0.500, total= 7.3min
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  7.3min remaining:    0.0s


[CV] .................................... , score=0.500, total= 7.2min
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed: 14.4min remaining:    0.0s


[CV] .................................... , score=0.500, total= 7.3min
Algo:  RFC :: 0.5001406039841858


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed: 21.8min finished


In [15]:
# Accuracy score
scoring =  accuracy_score
print("Scores without StandardScale")
cv_auc_score(models, scoring=scoring, num_folds=num_folds)

Scores without StandardScale
-> 3-Fold cross-validation  accuracy_score score for the training data for 4 classifiers.
[CV]  ................................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .................................... , score=0.911, total= 2.1min
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  2.1min remaining:    0.0s


[CV] .................................... , score=0.916, total= 2.1min
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  4.2min remaining:    0.0s


[CV] .................................... , score=0.913, total= 2.0min
Algo:  LR :: 0.9136142831544322
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:  6.2min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .................................... , score=0.831, total= 2.7min
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  2.7min remaining:    0.0s


[CV] .................................... , score=0.838, total= 3.0min
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  5.6min remaining:    0.0s


[CV] .................................... , score=0.834, total= 2.9min
Algo:  CART :: 0.834328570085126
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:  8.5min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .................................... , score=0.919, total=   1.2s
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.2s remaining:    0.0s


[CV] .................................... , score=0.923, total=   1.3s
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    2.5s remaining:    0.0s


[CV] .................................... , score=0.922, total=   1.1s
Algo:  NB :: 0.9213500026450546
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    3.6s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .................................... , score=0.899, total= 9.2min
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  9.2min remaining:    0.0s


[CV] .................................... , score=0.902, total= 9.3min
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed: 18.6min remaining:    0.0s


[CV] .................................... , score=0.898, total=11.6min
Algo:  RFC :: 0.8995214183060002


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed: 30.1min finished


In [16]:
def classification_report_models(models,X_train, X_test, y_train, y_test ):
    for name, model in models:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        print(name, ':\n', confusion_matrix(y_test, y_pred))
        print(name,':\n',classification_report(y_test, y_pred))

In [20]:
print(" without StandardScale")

classification_report_models(models=models, X_train = X_train, X_test= X_test, y_train=y_train, y_test=y_test)

 without StandardScale
LR :
 [[53248   723]
 [ 4434  1595]]
LR :
               precision    recall  f1-score   support

           0       0.92      0.99      0.95     53971
           1       0.69      0.26      0.38      6029

    accuracy                           0.91     60000
   macro avg       0.81      0.63      0.67     60000
weighted avg       0.90      0.91      0.90     60000

CART :
 [[48819  5152]
 [ 4770  1259]]
CART :
               precision    recall  f1-score   support

           0       0.91      0.90      0.91     53971
           1       0.20      0.21      0.20      6029

    accuracy                           0.83     60000
   macro avg       0.55      0.56      0.56     60000
weighted avg       0.84      0.83      0.84     60000

NB :
 [[53105   866]
 [ 3860  2169]]
NB :
               precision    recall  f1-score   support

           0       0.93      0.98      0.96     53971
           1       0.71      0.36      0.48      6029

    accuracy              

In [21]:
tr_X = train.drop([ 'ID_code'], axis=1)
test_X = test.drop(['ID_code'], axis=1)
for col in tr_X.drop(['target'], axis=1).columns:
    tr_X[col] = ((tr_X[col] - tr_X[col].mean()) / tr_X[col].std()).astype('float32')
for col in test_X.columns:
    test_X[col] = ((test_X[col] - test_X[col].mean()) / test_X[col].std()).astype('float32')
  

#Training data
X=tr_X.drop(['target'],axis=1)
Y=train['target']
#StratifiedKFold cross validator
cv=StratifiedKFold(n_splits=5,random_state=147,shuffle=True)
for train_index,valid_index in cv.split(X,Y):
    X_train1, X_valid=X.iloc[train_index], X.iloc[valid_index]
    y_train1, y_valid=Y.iloc[train_index], Y.iloc[valid_index]

print('Shape of X_train :',X_train1.shape)
print('Shape of X_valid :',X_valid.shape)
print('Shape of y_train :',y_train1.shape)
print('Shape of y_valid :',y_valid.shape)

Shape of X_train : (160000, 200)
Shape of X_valid : (40000, 200)
Shape of y_train : (160000,)
Shape of y_valid : (40000,)


In [22]:
#Synthetic Minority Oversampling Technique
sm = SMOTE(random_state=147)
#Generating synthetic data points
X_smote,y_smote=sm.fit_sample(X_train1,y_train1)
X_smote_v,y_smote_v=sm.fit_sample(X_valid,y_valid)

In [23]:
def classification_report_models(models,X_train = X_smote, X_test= X_smote_v, y_train=y_smote, y_test=y_smote_v):
    for name, model in models:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        print(name, ':\n', confusion_matrix(y_test, y_pred))
        print(name,':\n',classification_report(y_test, y_pred))

In [25]:

classification_report_models(models=models, X_train = X_smote, X_test= X_smote_v, y_train=y_smote, y_test=y_smote_v)

LR :
 [[28535  7445]
 [ 7688 28292]]
LR :
               precision    recall  f1-score   support

           0       0.79      0.79      0.79     35980
           1       0.79      0.79      0.79     35980

    accuracy                           0.79     71960
   macro avg       0.79      0.79      0.79     71960
weighted avg       0.79      0.79      0.79     71960

CART :
 [[26718  9262]
 [18362 17618]]
CART :
               precision    recall  f1-score   support

           0       0.59      0.74      0.66     35980
           1       0.66      0.49      0.56     35980

    accuracy                           0.62     71960
   macro avg       0.62      0.62      0.61     71960
weighted avg       0.62      0.62      0.61     71960

NB :
 [[34250  1730]
 [ 7578 28402]]
NB :
               precision    recall  f1-score   support

           0       0.82      0.95      0.88     35980
           1       0.94      0.79      0.86     35980

    accuracy                           0.87     7

In [17]:
 !pip install lightgbm

In [26]:
import lightgbm as lgb

In [27]:
#Training the model with simple train_test_split stratified data
#training data

lgb_train=lgb.Dataset(X_train,label=y_train)
#validation data
lgb_valid=lgb.Dataset(X_test,label=y_test)

In [28]:
params={'boosting_type': 'gbdt', 
          'max_depth' : -1, #no limit for max_depth if <0
          'objective': 'binary',
          'boost_from_average':False, 
          'nthread': 20,
          'metric':'auc',
          'num_leaves': 50,
          'learning_rate': 0.01,
          'max_bin': 100,      #default 255
          'subsample_for_bin': 100,
          'subsample': 1,
          'subsample_freq': 1,
          'colsample_bytree': 0.8,
          'bagging_fraction':0.5,
          'bagging_freq':5,
          'feature_fraction':0.08,
          'min_split_gain': 0.45, #>0
          'min_child_weight': 1,
          'min_child_samples': 5,
          'is_unbalance':True,
          }

In [29]:

def lgb_f1_score(y_hat, data):
    y_true = data.get_label()
    y_hat = np.round(y_hat) # scikits f1 doesn't like probabilities
    return 'f1', f1_score(y_true, y_hat), True

evals_result = {}

In [30]:
num_rounds=1000
lgbm1= lgb.train(params,lgb_train,num_rounds,valid_sets=[lgb_train,lgb_valid],feval=lgb_f1_score,verbose_eval=100,early_stopping_rounds = 500)

Training until validation scores don't improve for 500 rounds
[100]	training's auc: 0.90473	training's f1: 0.501978	valid_1's auc: 0.861808	valid_1's f1: 0.453369
[200]	training's auc: 0.916043	training's f1: 0.520313	valid_1's auc: 0.871636	valid_1's f1: 0.463072
[300]	training's auc: 0.921524	training's f1: 0.530338	valid_1's auc: 0.874694	valid_1's f1: 0.471082
[400]	training's auc: 0.925516	training's f1: 0.538659	valid_1's auc: 0.877351	valid_1's f1: 0.475187
[500]	training's auc: 0.929301	training's f1: 0.544808	valid_1's auc: 0.879744	valid_1's f1: 0.476082
[600]	training's auc: 0.933148	training's f1: 0.550923	valid_1's auc: 0.881459	valid_1's f1: 0.481687
[700]	training's auc: 0.935784	training's f1: 0.555645	valid_1's auc: 0.882739	valid_1's f1: 0.484115
[800]	training's auc: 0.938713	training's f1: 0.562333	valid_1's auc: 0.884134	valid_1's f1: 0.486005
[900]	training's auc: 0.941561	training's f1: 0.570638	valid_1's auc: 0.885102	valid_1's f1: 0.489819
[1000]	training's auc

In [31]:
print('Confusion matrix: Simple Lightgbm')
confusion_matrix(y_test, lgbm1.predict(X_test).round())

Confusion matrix: Simple Lightgbm


array([[46422,  7549],
       [ 1609,  4420]], dtype=int64)

In [32]:
#Training the model with StratifiedKFold()+SMOTE() data
#training data
lgb_train2=lgb.Dataset(X_smote,label=y_smote)
#validation data
lgb_valid2=lgb.Dataset(X_smote_v,label=y_smote_v)

In [34]:
num_rounds=10000
lgbm3= lgb.train(params,lgb_train2,num_rounds,valid_sets=[lgb_train2,lgb_valid2],feval=lgb_f1_score,verbose_eval=1000,early_stopping_rounds = 5000)

Training until validation scores don't improve for 5000 rounds
[1000]	training's auc: 0.956207	training's f1: 0.885727	valid_1's auc: 0.93558	valid_1's f1: 0.854468
[2000]	training's auc: 0.969384	training's f1: 0.906972	valid_1's auc: 0.944535	valid_1's f1: 0.867009
[3000]	training's auc: 0.977196	training's f1: 0.920779	valid_1's auc: 0.948302	valid_1's f1: 0.871963
[4000]	training's auc: 0.982755	training's f1: 0.931635	valid_1's auc: 0.950366	valid_1's f1: 0.874556
[5000]	training's auc: 0.987019	training's f1: 0.940849	valid_1's auc: 0.951436	valid_1's f1: 0.875119
[6000]	training's auc: 0.990332	training's f1: 0.949184	valid_1's auc: 0.952014	valid_1's f1: 0.875143
[7000]	training's auc: 0.992891	training's f1: 0.957019	valid_1's auc: 0.952321	valid_1's f1: 0.875251
[8000]	training's auc: 0.99484	training's f1: 0.963922	valid_1's auc: 0.952444	valid_1's f1: 0.875006
[9000]	training's auc: 0.996309	training's f1: 0.97027	valid_1's auc: 0.95262	valid_1's f1: 0.874528
[10000]	traini

In [35]:
# confusion matrix
print('Confusion matrix: SMOTE Lightgbm')
confusion_matrix(y_test, lgbm3.predict(X_test).round())
#plot_roc(y_test,  lgbm3.predict(X_test).round(), name='SMOTE LightGBM')

Confusion matrix: SMOTE Lightgbm


array([[53971,     0],
       [ 6029,     0]], dtype=int64)

In [36]:

#final submission

X_test=test.drop(['ID_code'],axis=1)
#predict the model, probability predictions
lightgbm_predict_prob3=lgbm3.predict(X_test,random_state=42,num_iteration=lgbm3.best_iteration)
lightgbm_predict_prob1=lgbm1.predict(X_test,random_state=42,num_iteration=lgbm1.best_iteration)

#Convert to binary output 1 or 0
lightgbm_predict3=lightgbm_predict_prob3.round()
lightgbm_predict1=lightgbm_predict_prob1.round()

In [37]:
submit=pd.DataFrame({'ID_code':test['ID_code'].values})
submit1=pd.DataFrame({'ID_code':test['ID_code'].values})

#submit['lightgbm_predict_prob']=lightgbm_predict_prob3
submit['target']=lightgbm_predict3.astype(int)
submit1['target']=lightgbm_predict1.astype(int)

submit.to_csv('submission.csv',index=False)
submit1.to_csv('submission1.csv',index=False)



ID_code  target
0  test_0       0
1  test_1       0
2  test_2       0
3  test_3       0
4  test_4       0

In [39]:
submit1.head()

ID_code  target
0  test_0       0
1  test_1       1
2  test_2       1
3  test_3       1
4  test_4       0

In [38]:
submit.head()

ID_code  target
0  test_0       0
1  test_1       0
2  test_2       0
3  test_3       0
4  test_4       0